# Generated by Django 2.2.3 on 2020-09-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FastFoodProducts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('price', models.CharField(default='', max_length=50)),
                ('date_epoch', models.CharField(default='', max_length=100)),
                ('category', models.CharField(default='', max_length=50)),
                ('image_url1', models.CharField(default='', max_length=100)),
                ('image_url2', models.CharField(default='', max_length=100)),
                ('image_url3', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=10000)),
            ],
        ),
    ]
