# Generated by Django 2.2.3 on 2020-02-29 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buxsbackend', '0003_marketplaceproducts_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplaceproducts',
            name='owner',
        ),
    ]
