# Generated by Django 2.2.3 on 2020-03-06 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buxsbackend', '0004_remove_marketplaceproducts_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketPlaceProducts',
        ),
    ]
