# Generated by Django 2.2.3 on 2020-03-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketplaceproducts',
            old_name='image_url',
            new_name='image_url1',
        ),
        migrations.AddField(
            model_name='marketplaceproducts',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='marketplaceproducts',
            name='image_url2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='marketplaceproducts',
            name='image_url3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='marketplaceproducts',
            name='stock',
            field=models.IntegerField(default=50),
        ),
    ]
