# Generated by Django 2.2.3 on 2020-03-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0004_marketplaceproducts_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceproducts',
            name='description',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='marketplaceproducts',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
